DROP TABLE IF EXIST driver;
CREATE TABLE driver(
    driverId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(20) NOT NULL UNIQUE,
    lastName VARCHAR(20) NOT NULL UNIQUE,
    distance INT NOT NULL,
    salary DECIMAL NOT NULL
);
DROP TABLE IF EXISTS car;
CREATE TABLE car (
    carId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nameCar INT NOT NULL,
    modelCar VARCHAR(20) NOT NULL UNIQUE,
    typeCar VARCHAR(20) NOT NULL UNIQUE,
    driverId INT NOT NULL
);
)